contentColumnType: text
fieldGroup: c8421b67-8b75-4524-a993-69af8adfe49f # Beer
handle: bigLayout
instructions: ''
name: 'Big Layout'
searchable: false
settings:
  cols: 30
  defaultValue: 1|3|1|3
  rows: 4
translationKeyFormat: null
translationMethod: none
type: wbrowar\littlelayout\fields\Layout
