contentColumnType: string
fieldGroup: c8421b67-8b75-4524-a993-69af8adfe49f # Beer
handle: featuredProducts
instructions: ''
name: 'Featured Products'
searchable: false
settings:
  contentTable: '{{%matrixcontent_featuredproducts}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
