columnSuffix: null
contentColumnType: text
fieldGroup: c8421b67-8b75-4524-a993-69af8adfe49f # Beer
handle: layout
instructions: 'Lay out image on featured products grid.'
name: Layout
searchable: false
settings:
  clearable: '1'
  cols: '6'
  defaultValue: 2|4|2|2
  rows: '3'
  selectionMode: box
translationKeyFormat: null
translationMethod: none
type: wbrowar\littlelayout\fields\Layout
