contentColumnType: text
fieldGroup: c8421b67-8b75-4524-a993-69af8adfe49f # Beer
handle: myLayoutField
instructions: ''
name: 'My Layout Field'
searchable: false
settings:
  cols: '3'
  defaultValue: ''
  rows: '1'
translationKeyFormat: null
translationMethod: none
type: wbrowar\littlelayout\fields\Layout
