contentColumnType: string
fieldGroup: c8421b67-8b75-4524-a993-69af8adfe49f # Beer
handle: tallLayout
instructions: ''
name: 'Tall Layout'
searchable: false
settings:
  cols: '1'
  defaultValue: ''
  rows: '10'
translationKeyFormat: null
translationMethod: none
type: wbrowar\littlelayout\fields\Layout
