dateModified: 1617762215
email:
  fromEmail: email@example.com
  fromName: 'Craft Plugin'
  transportType: craft\mail\transportadapters\Sendmail
plugins:
  cp-field-inspect:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  little-layout:
    edition: standard
    enabled: true
    licenseKey: $PLUGIN_LICENSE_KEY
    schemaVersion: 1.0.0
system:
  edition: pro
  live: true
  name: 'Craft Plugin'
  schemaVersion: 3.6.6
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
