field: 6309a141-3408-4e4b-9d78-83bb6b2ce0c8 # Featured Products
fieldLayouts:
  cef686e2-c08c-465f-a58d-5b7f2aee7afe:
    tabs:
      -
        elements:
          -
            fieldUid: 649d744b-d6ae-4e90-a0c5-0e022ce2e0a5 # Product Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: fcb15b2b-1d74-44ef-9818-130ca586ebc0 # Layout
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: b92add05-aaf4-4a80-afa2-39aba52c1f5a # Text Align
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 283e606d-1524-4391-80d3-3480252f555c # Vertical Align
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
        name: Content
        sortOrder: 1
fields:
  283e606d-1524-4391-80d3-3480252f555c: # Vertical Align
    contentColumnType: text
    fieldGroup: null
    handle: verticalAlign
    instructions: ''
    name: 'Vertical Align'
    searchable: false
    settings:
      clearable: 1
      cols: 1
      defaultValue: ''
      rows: 3
    translationKeyFormat: null
    translationMethod: none
    type: wbrowar\littlelayout\fields\Layout
  649d744b-d6ae-4e90-a0c5-0e022ce2e0a5: # Product Name
    contentColumnType: text
    fieldGroup: null
    handle: productName
    instructions: ''
    name: 'Product Name'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  b92add05-aaf4-4a80-afa2-39aba52c1f5a: # Text Align
    contentColumnType: text
    fieldGroup: null
    handle: textAlign
    instructions: ''
    name: 'Text Align'
    searchable: false
    settings:
      clearable: 2
      cols: 3
      defaultValue: 1|1|1|1
      rows: 1
    translationKeyFormat: null
    translationMethod: none
    type: wbrowar\littlelayout\fields\Layout
  fcb15b2b-1d74-44ef-9818-130ca586ebc0: # Layout
    contentColumnType: text
    fieldGroup: null
    handle: layout
    instructions: ''
    name: Layout
    searchable: false
    settings:
      clearable: 2
      cols: 6
      defaultValue: 1|6|1|1
      rows: 1
    translationKeyFormat: null
    translationMethod: none
    type: wbrowar\littlelayout\fields\Layout
handle: productName
name: 'Product Name'
sortOrder: 1
